import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import React from "react";
import {Navbar, NavbarBrand, NavbarContent, NavbarItem, Link, Button} from "@nextui-org/react";

import { api } from '~/utils/api';

const NavLogo: React.FC = () => <svg fill="none" height="36" viewBox="0 0 32 32" width="36">
<path
  clipRule="evenodd"
  d="M17.6482 10.1305L15.8785 7.02583L7.02979 22.5499H10.5278L17.6482 10.1305ZM19.8798 14.0457L18.11 17.1983L19.394 19.4511H16.8453L15.1056 22.5499H24.7272L19.8798 14.0457Z"
  fill="currentColor"
  fillRule="evenodd"
/>
</svg>

const Nav: React.FC = () => {
	return (
		<Navbar>
			<NavbarBrand>
				<NavLogo />
				<p className="font-bold text-inherit">Quandry</p>
			</NavbarBrand>
			<NavbarContent>

			</NavbarContent>


		</Navbar>
	)
}

export default function Home() {
	const hello = api.post.hello.useQuery({ text: 'from tRPC' });
	return (
		<>
			<Head>
				<title>Quandry</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Nav />
			<main className="flex min-h-screen flex-col bg-slate-200">
				<h1 className="text-3xl text-slate-700 p-5">Quandry</h1>
			</main>
		</>
	);
}

function AuthShowcase() {
	const { data: sessionData } = useSession();

	const { data: secretMessage } = api.post.getSecretMessage.useQuery(
		undefined, // no input
		{ enabled: sessionData?.user !== undefined }
	);

	return (
		<div className="flex flex-col items-center justify-center gap-4">
			<p className="text-center text-2xl text-white">
				{sessionData && (
					<span>Logged in as {sessionData.user?.name}</span>
				)}
				{secretMessage && <span> - {secretMessage}</span>}
			</p>
			<button
				className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
				onClick={
					sessionData ? () => void signOut() : () => void signIn()
				}
			>
				{sessionData ? 'Sign out' : 'Sign in'}
			</button>
		</div>
	);
}
